name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # ← mainブランチにpushされたら実行（変更可能）

jobs:
  deploy:
    name: Deploy Worker
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Verify secrets
        run: |
          echo "CLOUDFLARE_API_TOKEN: ✅"
          echo "CLOUDFLARE_ACCOUNT_ID: ✅"

      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler deploy
